project:
  type: website
  pre-render: R/preRender.R

website:
  title: "dep-seacar-data-compare"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: provider_reports/provider_reports.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



