project:
  type: website
  pre-render: R/preRender.R

website:
  title: "dep-seacar-data-compare"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: provider_reports/provider_reports.qmd
      - href: https://github.com/USF-IMARS/dep-seacar-data-compare
        text: Source Code on GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



